version: '3.7'

volumes:
  exness_test_backend_postgres_std:
    name: exness-test-backend-postgres-std

networks:
  exness_test_backend:
    name: exness-test-backend
    driver: bridge

services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - exness_test_backend_postgres_std:/var/lib/postgresql/data
    ports:
      - 6432:5432
    networks:
      - exness_test_backend
